theme: jekyll-theme-minimal
title: Nicholas Barrios
description: Hi there! I'm a software developer in Los Angeles, CA. This is collection of links to my work.
github:
  is_project_page: false
  is_user_page: true
